name: "Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Install dependencies'
        # Pin pydantic - bump-my-version incompat with v > 2
        run: |
          pip install "pydantic<2.0.0"
          pip install bump-my-version

      - name: Bump and tag version
        id: bump_version
        run: |
          echo "prev_version=$(bump-my-version show current_version)" >> "$GITHUB_OUTPUT"
          bump-my-version ${{ github.event.inputs.release_type}}
          echo "release_version=$(bump-my-version show current_version)" >> "$GITHUB_OUTPUT"

      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version ${{ steps.bump_version.outputs.prev_version }} → ${{ steps.bump_version.outputs.release_version }}"
          tagging_message: "v${{ steps.bump_version.outputs.release_version}}"

      - name: publish to pypi
        env:
          FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: |
          pip install flit
          flit publish
